// <auto-generated />
using System;
using FiltroDotnet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiltroDotnet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241007154929_AddTableUser")]
    partial class AddTableUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FiltroDotnet.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<int>("GuestId")
                        .HasColumnType("int")
                        .HasColumnName("guest_id");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_cost");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("GuestId");

                    b.HasIndex("RoomId");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("FiltroDotnet.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("identification_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("FiltroDotnet.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birthdate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("identification_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("guests");
                });

            modelBuilder.Entity("FiltroDotnet.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Availability")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("availability");

                    b.Property<int>("MaxOccupancyPersons")
                        .HasColumnType("int")
                        .HasColumnName("max_occupancy_persons");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_per_night");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("room_number");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = true,
                            MaxOccupancyPersons = 1,
                            PricePerNight = 50m,
                            RoomNumber = "F1R1",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 80m,
                            RoomNumber = "F1R2",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 150m,
                            RoomNumber = "F1R3",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Availability = true,
                            MaxOccupancyPersons = 4,
                            PricePerNight = 200m,
                            RoomNumber = "F1R4",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Availability = true,
                            MaxOccupancyPersons = 1,
                            PricePerNight = 50m,
                            RoomNumber = "F1R5",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 80m,
                            RoomNumber = "F1R6",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 150m,
                            RoomNumber = "F1R7",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            Availability = true,
                            MaxOccupancyPersons = 4,
                            PricePerNight = 200m,
                            RoomNumber = "F1R8",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 9,
                            Availability = true,
                            MaxOccupancyPersons = 1,
                            PricePerNight = 50m,
                            RoomNumber = "F1R9",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 80m,
                            RoomNumber = "F1R10",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 150m,
                            RoomNumber = "F2R1",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 12,
                            Availability = true,
                            MaxOccupancyPersons = 4,
                            PricePerNight = 200m,
                            RoomNumber = "F2R2",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 13,
                            Availability = true,
                            MaxOccupancyPersons = 1,
                            PricePerNight = 50m,
                            RoomNumber = "F2R3",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 80m,
                            RoomNumber = "F2R4",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 15,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 150m,
                            RoomNumber = "F2R5",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 16,
                            Availability = true,
                            MaxOccupancyPersons = 4,
                            PricePerNight = 200m,
                            RoomNumber = "F2R6",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 17,
                            Availability = true,
                            MaxOccupancyPersons = 1,
                            PricePerNight = 50m,
                            RoomNumber = "F2R7",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 18,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 80m,
                            RoomNumber = "F2R8",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 19,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 150m,
                            RoomNumber = "F2R9",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 20,
                            Availability = true,
                            MaxOccupancyPersons = 4,
                            PricePerNight = 200m,
                            RoomNumber = "F2R10",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 21,
                            Availability = true,
                            MaxOccupancyPersons = 1,
                            PricePerNight = 50m,
                            RoomNumber = "F3R1",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 22,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 80m,
                            RoomNumber = "F3R2",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 23,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 150m,
                            RoomNumber = "F3R3",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 24,
                            Availability = true,
                            MaxOccupancyPersons = 4,
                            PricePerNight = 200m,
                            RoomNumber = "F3R4",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 25,
                            Availability = true,
                            MaxOccupancyPersons = 1,
                            PricePerNight = 50m,
                            RoomNumber = "F3R5",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 26,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 80m,
                            RoomNumber = "F3R6",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 27,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 150m,
                            RoomNumber = "F3R7",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 28,
                            Availability = true,
                            MaxOccupancyPersons = 4,
                            PricePerNight = 200m,
                            RoomNumber = "F3R8",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 29,
                            Availability = true,
                            MaxOccupancyPersons = 1,
                            PricePerNight = 50m,
                            RoomNumber = "F3R9",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 30,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 80m,
                            RoomNumber = "F3R10",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 31,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 150m,
                            RoomNumber = "F4R1",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 32,
                            Availability = true,
                            MaxOccupancyPersons = 4,
                            PricePerNight = 200m,
                            RoomNumber = "F4R2",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 33,
                            Availability = true,
                            MaxOccupancyPersons = 1,
                            PricePerNight = 50m,
                            RoomNumber = "F4R3",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 34,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 80m,
                            RoomNumber = "F4R4",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 35,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 150m,
                            RoomNumber = "F4R5",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 36,
                            Availability = true,
                            MaxOccupancyPersons = 4,
                            PricePerNight = 200m,
                            RoomNumber = "F4R6",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 37,
                            Availability = true,
                            MaxOccupancyPersons = 1,
                            PricePerNight = 50m,
                            RoomNumber = "F4R7",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 38,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 80m,
                            RoomNumber = "F4R8",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 39,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 150m,
                            RoomNumber = "F4R9",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 40,
                            Availability = true,
                            MaxOccupancyPersons = 4,
                            PricePerNight = 200m,
                            RoomNumber = "F4R10",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 41,
                            Availability = true,
                            MaxOccupancyPersons = 1,
                            PricePerNight = 50m,
                            RoomNumber = "F5R1",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 42,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 80m,
                            RoomNumber = "F5R2",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 43,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 150m,
                            RoomNumber = "F5R3",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 44,
                            Availability = true,
                            MaxOccupancyPersons = 4,
                            PricePerNight = 200m,
                            RoomNumber = "F5R4",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 45,
                            Availability = true,
                            MaxOccupancyPersons = 1,
                            PricePerNight = 50m,
                            RoomNumber = "F5R5",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 46,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 80m,
                            RoomNumber = "F5R6",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 47,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 150m,
                            RoomNumber = "F5R7",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 48,
                            Availability = true,
                            MaxOccupancyPersons = 4,
                            PricePerNight = 200m,
                            RoomNumber = "F5R8",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 49,
                            Availability = true,
                            MaxOccupancyPersons = 1,
                            PricePerNight = 50m,
                            RoomNumber = "F5R9",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 50,
                            Availability = true,
                            MaxOccupancyPersons = 2,
                            PricePerNight = 80m,
                            RoomNumber = "F5R10",
                            RoomTypeId = 2
                        });
                });

            modelBuilder.Entity("FiltroDotnet.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("room_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Una acogedora habitación básica con una cama individual, ideal para viajeros solos.",
                            Name = "Simple"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ofrece flexibilidad con dos camas individuales o una cama doble, perfecta para parejas o amigos.",
                            Name = "Doble"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Espaciosa y lujosa, con una cama king size y una sala de estar separada, ideal para quienes buscan confort y exclusividad.",
                            Name = "Suite"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Diseñada para familias, con espacio adicional y varias camas para una estancia cómoda.",
                            Name = "Familiar"
                        });
                });

            modelBuilder.Entity("FiltroDotnet.Models.Booking", b =>
                {
                    b.HasOne("FiltroDotnet.Models.Employee", "Employee")
                        .WithMany("Bookings")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiltroDotnet.Models.Guest", "Guest")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiltroDotnet.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Guest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("FiltroDotnet.Models.Room", b =>
                {
                    b.HasOne("FiltroDotnet.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("FiltroDotnet.Models.Employee", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("FiltroDotnet.Models.Guest", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("FiltroDotnet.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("FiltroDotnet.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
